import type { TraceIdV1 } from "./ids.js";

export const SHARED_ERROR_CODES_V1 = [
  "INVALID_REQUEST", "UNSUPPORTED_CONTRACT_VERSION", "SESSION_NOT_FOUND", "SESSION_EXPIRED",
  "SESSION_CANCELLED", "INVALID_SESSION_STATE", "DUPLICATE_REQUEST", "IDEMPOTENCY_CONFLICT",
  "OPERATION_IN_PROGRESS", "OPERATION_RECOVERY_REQUIRED", "TURN_LIMIT_REACHED", "TEST_NOT_AVAILABLE",
  "TEST_ALREADY_COMPLETED", "DIAGNOSIS_ALREADY_SUBMITTED", "MODEL_TIMEOUT", "MODEL_UNAVAILABLE",
  "EVALUATION_UNAVAILABLE", "STREAM_INTERRUPTED", "SAFETY_REAL_HEALTH_INPUT", "SAFETY_PROMPT_INJECTION", "SAFETY_INTERRUPTED",
  "INTERNAL_ERROR",
] as const;
export type SharedErrorCodeV1 = (typeof SHARED_ERROR_CODES_V1)[number];
export type SharedErrorV1 = {
  code: SharedErrorCodeV1;
  message: string;
  retryable: boolean;
  traceId?: TraceIdV1;
  details?: Record<string, unknown>;
};
